### ISSUE TITLE
Enroll by Asset Tag not working v0.71a

### ISSUE THREAD

**Issue by David-Promevo** [google/loaner#69] opened 2019-09-10 13:08 UTC
### Expected Behaviour
Enrollment is available via Asset Tag (by changing the option in the Web App Config.
### Actual Behaviour
Enrollment is available via Asset Tag.
### Steps to Reproduce
Web App > Config > Device Identifier Mode > Toggle Asset Tag > Save Changes
Devices > Enroll > Enter Asset ID > Save
Error: "ERROR: No serial number for device [asset tag]"

When enrolling a device w/ an Asset Tag via the Serial Number Method there is no entry for Asset Tag [Asset Tag: Empty] in the Datastore for the device.

chromedevices.list shows the following for the device.  I am using the "annotatedAssetId" field. 

{
   "kind": "admin#directory#chromeosdevice",
   "etag": "\"SXFHf-A4wQx02aM-7Cegj6o2Lk8/zank_9vd8n3IpzA9INHt3gyhMgk\"",
   "deviceId": "0a08a7c9-3449-4de9-aa9d-7c0f6724dd55",
   "serialNumber": "F4NLCX124647168",
   "status": "ACTIVE",
   "lastSync": "2017-05-22T14:24:51.698Z",
   "annotatedUser": "promevo.admin@chromebooktrial.promevo.com",
   "annotatedAssetId": "1000005",
   "notes": "",
   "model": "ASUS Chromebook C201PA",
   "osVersion": "57.0.2987.146",
   "platformVersion": "9202.64.0 (Official Build) stable-channel veyron_speedy",
   "firmwareVersion": "Google_Veyron_Speedy.6588.237.0",
   "macAddress": "28c2dd0ea225",
   "bootMode": "Verified",
   "lastEnrollmentTime": "2017-04-18T13:22:20.385Z",
   "orgUnitPath": "/", 
... etc.}

**Comment by lukehawkins94** [comment] 2019-09-11 13:41
Refer to https://github.com/google/loaner/issues/47 for workaround at the moment if you need to get it working asap for auditing purposes.

**Comment by helfrichmichael** [comment] 2020-04-03 15:37
This is a dupe of #47. Resolving and closing.

**Closed by helfrichmichael** 2020-04-03 15:37 UTC
Labels: duplicate
