### ISSUE TITLE
Bootstrap first access error

### ISSUE THREAD

**Issue by antoine-castex** [google/loaner#20] opened 2018-11-07 10:20 UTC
Hello

just have deploy for the first time the application

try connecting to do the boostrap and got  : 

The server has either erred or is incapable of performing the requested operation.

Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/3b44e98ed7fbb86b/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/3b44e98ed7fbb86b/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/3b44e98ed7fbb86b/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/3b44e98ed7fbb86b/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/3b44e98ed7fbb86b/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/3b44e98ed7fbb86b/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~gbl-ist-ve-grabngo/deploy-first.413797860836212450/loaner/web_app/backend/handlers/frontend.py", line 74, in get
    self._sync_roles_if_necessary()
  File "/base/data/home/apps/s~gbl-ist-ve-grabngo/deploy-first.413797860836212450/loaner/web_app/backend/handlers/frontend.py", line 99, in _sync_roles_if_necessary
    sync_users.sync_user_roles()
  File "/base/data/home/apps/s~gbl-ist-ve-grabngo/deploy-first.413797860836212450/loaner/web_app/backend/lib/sync_users.py", line 36, in sync_user_roles
    constants.SUPERADMINS_GROUP)
  File "/base/data/home/apps/s~gbl-ist-ve-grabngo/deploy-first.413797860836212450/loaner/web_app/backend/clients/directory.py", line 337, in get_all_users_in_group
    response = self._users_in_group(group_email)
  File "/base/data/home/apps/s~gbl-ist-ve-grabngo/deploy-first.413797860836212450/loaner/web_app/backend/clients/directory.py", line 379, in _users_in_group
    raise DirectoryRPCError(err.resp.reason)
DirectoryRPCError: Forbidden

**Comment by Sasho11** [comment] 2018-11-12 14:46
This usually means that the proper permission was not assigned in order for the directory api to manage users in your domain. Please make sure that you've done all of the steps in step 2 of https://github.com/google/loaner/blob/master/docs/setup_guide.md and double check that the correct scopes have been added for step 2v.

**Comment by BennyBoo85** [comment] 2018-11-16 20:31
@antoine-castex did you get this resolved yet? I'm running into the same issue and double checked my work.

**Comment by antoine-castex** [comment] 2018-11-19 07:38
> This usually means that the proper permission was not assigned in order for the directory api to manage users in your domain. Please make sure that you've done all of the steps in step 2 of https://github.com/google/loaner/blob/master/docs/setup_guide.md and double check that the correct scopes have been added for step 2v.

I have check with my team

the scope are 

admin.directory.device.chromeos
admin.directory.group.member.readonly
admin.directory.orgunit
admin.directory.user.readonly 

is that good ?

**Comment by antoine-castex** [comment] 2018-11-19 07:38
> @antoine-castex did you get this resolved yet? I'm running into the same issue and double checked my work.

problem still here :(

**Comment by antoine-castex** [comment] 2018-11-21 08:52
I can see the cron job in error for the same reason

Forbidden (/base/alloc/tmpfs/dynamic_runtimes/python27g/3b44e98ed7fbb86b/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py:1552)
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/3b44e98ed7fbb86b/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/3b44e98ed7fbb86b/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/3b44e98ed7fbb86b/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/3b44e98ed7fbb86b/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/3b44e98ed7fbb86b/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/3b44e98ed7fbb86b/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~gbl-ist-ve-grabngo/deploy-first.414093468639346751/loaner/web_app/backend/handlers/cron/sync_user_roles.py", line 31, in get
    sync_users.sync_user_roles()
  File "/base/data/home/apps/s~gbl-ist-ve-grabngo/deploy-first.414093468639346751/loaner/web_app/backend/lib/sync_users.py", line 36, in sync_user_roles
    constants.SUPERADMINS_GROUP)
  File "/base/data/home/apps/s~gbl-ist-ve-grabngo/deploy-first.414093468639346751/loaner/web_app/backend/clients/directory.py", line 337, in get_all_users_in_group
    response = self._users_in_group(group_email)
  File "/base/data/home/apps/s~gbl-ist-ve-grabngo/deploy-first.414093468639346751/loaner/web_app/backend/clients/directory.py", line 379, in _users_in_group
    raise DirectoryRPCError(err.resp.reason)
DirectoryRPCError: Forbidden

**Comment by antoine-castex** [comment] 2018-11-21 08:52
my grab n go gsuite account is owner the google group created

how can i have miss for permissions ?

**Comment by JoshSanchezG** [comment] 2018-11-21 23:16
Hello,

  Was anybody able to fix this issue? Thanks and regards!

**Comment by gyoshi02** [comment] 2018-12-14 01:20
Hello, 
Is there any update here? 
We are also stuck at this step.  You can click on the other sections of the application, but seems like we are missing a step somewhere...

**Comment by helfrichmichael** [comment] 2018-12-14 03:39
Sorry for the delay. Have you created a custom GSuite role to provide access to the Directory of GSuite? This is done with admin roles at the role account level.

https://support.google.com/a/answer/2406043?hl=en

Additionally, if you haven't yet, we recommend pulling from head as many bugs have been fixed since this issue was opened.

**Comment by gyoshi02** [comment] 2018-12-14 17:03
Hello, 
The we used a service account called svc-loaner-role@ that we created.  It does not have the super admin role, but it has elevated access.  
Groups Admin
User Managment 
Services Admin
A new Custom role that I created that gives the ability to create OUs and modify them. 
I can send a screen shot if needed, but this user has the ability to create/delete, and take all actions against users. 

What do you mean when you say pull from "head" ? 
I'm using Alpha-0.7
git clone -b Alpha-\(0.7\) https://github.com/google/loaner.git
Thanks,

**Comment by helfrichmichael** [comment] 2018-12-14 18:12
For the missing permissions, you're likely missing access to the GSuite Directory within the Admin API privileges (https://admin.google.com/AdminHome#DomainSettings/notab=1&subtab=roles). I believe the permissions in the screenshot below are accurate. You could also try temporarily providing super admin to the role-account to see if that remediates the issue to confirm the root cause of the issue.

![image](https://user-images.githubusercontent.com/9116898/50019715-ae117f80-ffa1-11e8-8285-d0f1394c084e.png)

As for pulling from HEAD, that's by using "git clone https://github.com/google/loaner.git" without the branch specification (will pull the latest changes).

**Comment by helfrichmichael** [comment] 2018-12-17 18:37
@gyoshi02 can you confirm the OU structure that you have and what you configured for the OU settings in the constants.py and config_defaults.yaml file?

**Comment by gyoshi02** [comment] 2018-12-17 18:56
@ helfrichmichael
Here's the OU Structure that we have in place: 
![image](https://user-images.githubusercontent.com/45863342/50107826-852efb80-01e8-11e9-9414-bb72eff1260c.png)
Here's the constants.py entries: 
![image](https://user-images.githubusercontent.com/45863342/50108197-814fa900-01e9-11e9-9ba6-fb66f933f446.png)
![image](https://user-images.githubusercontent.com/45863342/50108216-89a7e400-01e9-11e9-8321-3a84e279e013.png)
![image](https://user-images.githubusercontent.com/45863342/50108312-bf4ccd00-01e9-11e9-9f00-2e12f0c8cf1c.png)

So my config_defaults.yaml is default settings, as I thought we didn't have to update this yet. 
 " (Optional) Customize GnG Settings " I must have assumed it wasn't required. 
Should I update the OU setting here and try again?

**Comment by gyoshi02** [comment] 2018-12-17 19:45
So I updated the config_defaults.yaml to reflect some of the OU values and the technician email address.  Does the Org unit prefix (if I'm using root)  = /Grab n Go/Prod/ ? 
![image](https://user-images.githubusercontent.com/45863342/50111197-12764e00-01f1-11e9-9aa5-9248871b21a1.png)
Or is this value just "/" because we have created the /Grab n Go" OU right off of our Root within the domain? 
Also still getting that error as before. 
![image](https://user-images.githubusercontent.com/45863342/50111253-3c2f7500-01f1-11e9-81c9-76ea4530582f.png)

thanks,

**Comment by helfrichmichael** [comment] 2018-12-17 21:00
@gyoshi02 what are the errors in the Log Viewer on Google Cloud Platform for this error? Can you confirm that this is targeting PROD and not DEV/QA?

**Comment by gyoshi02** [comment] 2018-12-17 22:34
@helfrichmichael 

Here's a screen shot of something I found in the logs.  
![image](https://user-images.githubusercontent.com/45863342/50119832-bb7c7300-0208-11e9-9f45-f68a47389158.png)

I'm guessing this means I need to create all of the OUs, for Dev and QA(even though I'm not using them yet).
I'll try to re-deploy again, now that I've create these new OUs. 
Is there anything else that I should be looking for within these errors? 
Thanks,

**Comment by helfrichmichael** [comment] 2018-12-17 22:44
@gyoshi02 my major concern is that the app looks like it is targeting the dev version and not the prod version. This means the matcher isn't able to match the project ID to the instance you're running.

https://github.com/google/loaner/blob/master/loaner/web_app/constants.py#L75 is where we detect which version of the application you are running for the web app. Make sure that has the correct project name and that the settings are properly defined.

**Comment by gyoshi02** [comment] 2018-12-17 23:30
@helfrichmichael 
I missed your updated, and went ahead and created all of the additional OUs.  
We currently only have a project ID for Prod. 
I assumed that since we were not using QA and DEV, we shouldn't need to create them.  
I've got 4 green check marks now. 
![image](https://user-images.githubusercontent.com/45863342/50122261-765c3f00-0210-11e9-9ae9-3f779355f527.png)

We can begin testing enrollments and other parts of this project. 
Thanks for your assistance.

**Comment by helfrichmichael** [comment] 2018-12-19 21:15
I'm going to close this as we've addressed the culprit in this thread. If this reappears, please re-open.

**Closed by helfrichmichael** 2018-12-19 21:15 UTC
Labels: question
